### ISSUE TITLE
Download List not longer loading 

### ISSUE THREAD

**Issue by Whitedoteu** [fxsth/pledo#17]
I i think i killed to download list by adding to many items. 

The download is still running but i can not access the Download page. 
Also I'm not sure how to remove old items. So is my download list broken for ever?

I also could be because i added multiple of the same item. 
Not sure. The "have i clicked the session" conformation could be better :) 

Thank you for all the work :) 

<details>
<summary>Log DATA</summary>
<br>
Downloadlist Crashes
<br><br>
<pre>
 22:47:21
fail: Microsoft.AspNetCore.Server.Kestrel[13]
 22:47:21 Connection id "XXXX", Request id "XXXXXXXX": An unhandled exception was thrown by the application.
 22:47:21 System.NullReferenceException: Object reference not set to an instance of an object.
 22:47:21    at Web.Controllers.DownloadController.ToDownloadElementResource(DownloadElement x) in /src/Web/Controllers/DownloadController.cs:line 68
 22:47:21    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
 22:47:21    at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
 22:47:21    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
 22:47:21    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
 22:47:21    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
 22:47:21    at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
 22:47:21    at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo, WriteStack& state)
 22:47:21    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
 22:47:21    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
 22:47:21    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
 22:47:21    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
 22:47:21    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 22:47:21    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
 22:47:21    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
 22:47:21    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
 22:47:21 --- End of stack trace from previous location ---
 22:47:21    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 22:47:21    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
 22:47:21    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
 22:47:21    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
 22:47:21    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
 22:47:21    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
 22:47:21    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
</pre>
</details>

**Comment by Whitedoteu** [comment]
Restarting the Docker seems to fix it. 
Also now i also can not find the Limit again. 
I got the popup 2 time that i added to many to downloadlist. 

But i think this is because i clicked to fast?
Was still added to the List.

**Comment by fxsth** [comment]
Yes, probably thats the reason for the message. I'll look into it and try to improve the download section a bit.
Adding pagination should help reduce the unresponsivenes of the download page and confirmation / better response messages should give more information about starting the download.

When I find some spare time, Ill try to fix this :)
